//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetTrackerApp.MAUI.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetTrackerApp.MAUI.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track everything about your lovely friend!.
        /// </summary>
        public static string App_Slogan {
            get {
                return ResourceManager.GetString("App_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string PetGender_Female {
            get {
                return ResourceManager.GetString("PetGender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string PetGender_Male {
            get {
                return ResourceManager.GetString("PetGender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months old.
        /// </summary>
        public static string PetInfo_Age_MonthsOld {
            get {
                return ResourceManager.GetString("PetInfo_Age_MonthsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years old.
        /// </summary>
        public static string PetInfo_Age_YearsOld {
            get {
                return ResourceManager.GetString("PetInfo_Age_YearsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bird.
        /// </summary>
        public static string PetType_Bird {
            get {
                return ResourceManager.GetString("PetType_Bird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        public static string PetType_Cat {
            get {
                return ResourceManager.GetString("PetType_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        public static string PetType_Dog {
            get {
                return ResourceManager.GetString("PetType_Dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic pet.
        /// </summary>
        public static string PetType_ExoticPet {
            get {
                return ResourceManager.GetString("PetType_ExoticPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        public static string PetType_Fish {
            get {
                return ResourceManager.GetString("PetType_Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string PetType_Others {
            get {
                return ResourceManager.GetString("PetType_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabbit.
        /// </summary>
        public static string PetType_Rabbit {
            get {
                return ResourceManager.GetString("PetType_Rabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reptile.
        /// </summary>
        public static string PetType_Reptile {
            get {
                return ResourceManager.GetString("PetType_Reptile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmallMammal.
        /// </summary>
        public static string PetType_SmallMammal {
            get {
                return ResourceManager.GetString("PetType_SmallMammal", resourceCulture);
            }
        }
    }
}
